### ISSUE TITLE
Steamline release process using CI

### ISSUE THREAD

**Issue by fdocr** [forem/DEV-Android#81]
**Is your feature request related to a problem? Please describe.**
We want to better integrate CI tools to streamline the release process.

**Describe the solution you'd like**
#79 is a WIP PR that introduces Fastlane to integrate with Travis. Any help that can be provided here (conversation/suggestions) is greatly appreciated.

**TODO**:
- [x] Travis automated tests using Fastlane
- [x] Enable Travis for the project (in progress)
- [ ] A lane that allows Travis to upload a build to beta track in Google Play but never directly to production. Consider the API Keys used will only have permissions to upload to beta track
- [ ] Have Travis only upload to beta track when the commit message on master includes `[deploy]` or `[release]` in the commit message (i.e. [see this](https://github.com/thepracticaldev/dev.to/blob/master/.travis.yml#L78))
- [ ] Ensure all the sensitive files can be passed in as ENV Variables and are not visible in Travis logs

**Additional context**
As said before: #79 is a starting point but I could use some help from anyone that has better experience with this process 🙂

My main struggle has been with the keystore and making sure no credentials are logged when making the `fastlante beta` execution from within Travis.

**Comment by maestromac** [comment]
@fdoxyz Travis is enabled

**Comment by rt4914** [comment]
Closing this as it is not required now.
